sudo: false

addons:
  apt:
    packages:
      - "cmake"
      - "gfortran"
      - "liblapack-dev"
      - "libhdf5-serial-dev"

language: python

python:
  - "3.6"

before_install:
  - "bash .github/install_pyscf.sh"

install:
  - "pip install -r requirements.txt"

before_script:
  - "export PYTHONPATH=$HOME/pyscf:$PYTHONPATH"
  - "export PYTHONPATH=$(pwd):$PYTHONPATH"

script:
  - "make test"

# after_script:

cache:
  pip: true
  directories:
    - "$HOME/pyscf"
