dist: trusty
sudo: false
language: python
python:
  - 3.6

cache:
  timeout: 6000
  pip: true

install:
  - |
    if [ ! -d "$HOME/miniconda/bin" ]; then
        rm -rf $HOME/miniconda
        curl -s https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n p4env python=$TRAVIS_PYTHON_VERSION numpy scipy h5py psi4 psi4-rt -c psi4/label/dev -c psi4
  - source activate p4env
  - pip install -r requirements.txt
  - conda install -q -c conda-forge pytest-cov codecov
  - conda install -q -c pyscf pyscf
  - conda install -q -c conda-forge pytest-cov codecov sphinx sphinx-automodapi sphinx_rtd_theme numpydoc graphviz python-graphviz
  - pip install travis-sphinx
  - conda list

before_script:
  - mkdir "${HOME}/tmp"
  - |
    export PSI_SCRATCH="${HOME}"/tmp
    export "PYTHONPATH=$(pwd):$PYTHONPATH"
    export GH_REPO_NAME=pyresponse_docs
    export GH_REPO_SLUG=berquist/${GH_REPO_NAME}
    export GH_REPO_REF=github.com/${GH_REPO_SLUG}.git
    export DOCS_BRANCH_NAME=gh-pages
    export DOCS_DIR="${TRAVIS_BUILD_DIR}"/doc

script:
  - make test
  - travis-sphinx --verbose --outdir="${DOCS_DIR}"/build build --source="${DOCS_DIR}"/source --nowarn
  - install -dm755 "${DOCS_DIR}"/build/html
  - touch "${DOCS_DIR}"/build/html/.nojekyll
  - |
    if [[ "${TRAVIS_BRANCH}" == master ]]; then
        bash "${DOCS_DIR}"/deploy_pyresponse_docs_repo_travis-sphinx.bash
        # cd docs
        # bash ./deploy_pyresponse_docs_repo_travis.bash
        # cd ..
    fi

after_success:
  - codecov
