sudo: false
language: python
python:
  - 3.6

before_cache:
  - >-
    if [ ! -d "$HOME/miniconda" ]; then
        wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
    fi

cache:
  pip: true
  directories:
    - $HOME/miniconda

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n p4env python=$TRAVIS_PYTHON_VERSION numpy scipy h5py psi4 psi4-rt -c psi4/label/dev -c psi4
  - source activate p4env
  - pip install -r requirements.txt
  - conda install -q -c conda-forge pytest-cov codecov
  - conda install -q -c pyscf pyscf
  - conda list
  - mkdir "$HOME/tmp"
  - export PSI_SCRATCH="$HOME/tmp"

before_script:
  - export "PYTHONPATH=$(pwd):$PYTHONPATH"

script:
  - make test

after_success:
  - codecov
  - export GH_REPO_NAME=pyresponse_docs
  - export GH_REPO_REF=github.com/berquist/${GH_REPO_NAME}.git
  - export DOCS_BRANCH_NAME=master
  - if [[ $TRAVIS_BRANCH == master ]]; then cd docs; pip install Sphinx; bash ./deploy_pyresponse_docs_repo_travis.sh; fi
