---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  prechecks:
    uses: ./.github/workflows/pre-commit.yml
  separate-zizmor:
    uses: ./.github/workflows/zizmor.yml
  all-prechecks:
    needs: [prechecks, separate-zizmor]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
  unit-tests:
    needs: [all-prechecks]
    uses: ./.github/workflows/test_and_package.yml
  pixi:
    needs: [all-prechecks]
    uses: ./.github/workflows/pixi.yml
  publish:
    needs: [unit-tests, pixi]
    uses: ./.github/workflows/publish.yml
  all:
    needs: [unit-tests, pixi, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: "true"
