# yamllint disable-line rule:document-start
name: test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', 3.11]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} with conda
        # yamllint disable-line rule:comments rule:line-length
        uses: conda-incubator/setup-miniconda@29c004f57289f8b93aaebc627f7c4e0b6543e222 # v2.2.0
        with:
          activate-environment: test
          auto-activate-base: false
          auto-update-conda: true
          environment-file: devtools/conda-envs/test_env.yaml
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          show-channel-urls: true
      - name: Print Python environment
        run: python -m pip list
      - name: Print conda environment
        run: conda list
      - name: Print conda info
        run: conda info
      - name: Print conda config
        run: conda config --show
      - name: Run tests
        run: make test
      - name: Install
        run: python -m pip install .
      - name: Build documentation
        run: |
          cd docs
          make html
      - name: GitHub Pages deploy
        # yamllint disable-line rule:comments rule:line-length
        uses: JamesIves/github-pages-deploy-action@22a6ee251d6f13c6ab1ecb200d974f1a6feb1b8d # v4.4.2
        with:
          branch: gh-pages
          folder: docs/build/html
        # yamllint disable-line rule:line-length
        if: ${{ github.event_name == 'push' && matrix.python-version == '3.9' }}
